@node Fun between the parens, Index, The REPL, Top
@chapter Fun between the parens

I'm working on it... perhaps the
@uref{http://git.savannah.gnu.org/cgit/geiser.git/plain/README, README}
file will work for you in the meantime?


@c Local Variables:
@c mode: texinfo
@c TeX-master: "geiser"
@c End:
