@settitle Geiser

@include macros.texi

@contents

@node Top, Introduction, (dir), (dir)

@include top.texi
@html
<div class="version" align="right"><a class="navlink"
href="http://download.savannah.nongnu.org/releases/geiser/0.1/geiser-0.1.tar.gz">
Version 0.1, Dec 2010, Guile 1.9.14 and Racket 5.0.x
</a>
</div>
@end html

@menu
* Introduction::
* Installation::
* The REPL::
* Between the parens::
* Cheat sheet::
* No hacker is an island::
* Index::
@end menu

@html
<br/>
<div class="navigation" align="right">
<a class="navlink"
href="http://savannah.nongnu.org/news/?group=geiser">News</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="navlink"
href="http://savannah.nongnu.org/files/?group=geiser">Downloads</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="navlink"
href="http://savannah.nongnu.org/bugs/?group=geiser">Bugs</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="navlink"
href="http://git.savannah.gnu.org/cgit/geiser.git">Source</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="navlink"
href="http://lists.nongnu.org/mailman/listinfo/geiser-users">Mailing
list</a>&nbsp;
</div>
@end html

@include intro.texi
@include install.texi
@include repl.texi
@include parens.texi
@include cheat.texi
@include thanks.texi
@include index.texi

@bye

@c Local Variables:
@c mode: texinfo
@c TeX-master: t
@c End:
