@settitle Geiser

@include macros.texi

@contents

@node Top, Introduction, (dir), (dir)

@include top.texi
@vblurb{}

@menu
* Introduction::
* Installation::
* The REPL::
* Between the parens::
* Cheat sheet::
* No hacker is an island::
* Index::
@end menu

@html
<br/>
<div class="navigation" align="right">
<a class="navlink"
href="http://savannah.nongnu.org/news/?group=geiser">News</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="navlink"
href="http://savannah.nongnu.org/files/?group=geiser">Downloads</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="navlink"
href="https://github.com/jaor/geiser/issues">Bugs</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="navlink"
href="https://github.com/jaor/geiser.git">Source</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="navlink"
href="http://lists.nongnu.org/mailman/listinfo/geiser-users">Mailing
list</a>&nbsp;
</div>
@end html

@include intro.texi
@include install.texi
@include repl.texi
@include parens.texi
@include cheat.texi
@include thanks.texi
@include index.texi

@bye

@c Local Variables:
@c mode: texinfo
@c TeX-master: t
@c End:
